--- #YAML:1.0
name:               Opcodes
version:            0.08
abstract:           More Opcodes information from opnames.h and opcode.h
author:
    - Reini Urban
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/rurban/Opcodes
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
